FROM python:3.12-alpine

WORKDIR /app

# Evitar que Python escriba archivos .pyc y forzar logs en vivo
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Instalar dependencias del sistema necesarias para PostgreSQL y compilaciones
RUN apk add --no-cache gcc musl-dev postgresql-dev

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["python", "manage.py", "runserver", "0.0.0.0:5000"]